FROM node:21

WORKDIR /front-end

RUN npm install @angular/cli@17 -g

ENV APP_NAME 'login-angular17'
ENV ROUTING 'true'
ENV STANDALONE 'true'
ENV STRICT 'true'
ENV STYLE 'scss'

CMD ng new $APP_NAME --routing=$ROUTING --standalone=$STANDALONE --strict=$STRICT --style=$STYLE \
  && mv $APP_NAME/* . \
  && rm -rf $APP_NAME \ 
  && ng serve --host 0.0.0.0 --port 4200

EXPOSE 4200