version: '3.9'

services:
  container-angular:
    build: .
    container_name: container-angular
    working_dir: /login-angular17
    ports:
      - 4200:4200
      - 49153:49153
    volumes:
      - ./:/login-angular17
      - /login-angular17/node_modules
