version: '3.3'

services:
  container-angular:
    build: .
      # context: .
    container_name: container-angular
    ports:
      - 4200:4200
    volumes:
      - ./:/login-angular17
      - /login-angular17/node_modules
