version: '3'

services:
  container-angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-angular
    ports:
      - 4200:4200
    volumes:
      - ./:/home/node/app:cached

